#if !canImport(ObjectiveC)
import XCTest

extension SchemaObjectTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SchemaObjectTests = [
        ("test_jsonTypeFormat", test_jsonTypeFormat),
        ("test_notNullable", test_notNullable),
        ("test_notNullableToNullable", test_notNullableToNullable),
        ("test_nullable", test_nullable),
        ("test_optional", test_optional),
        ("test_optionalToRequired", test_optionalToRequired),
        ("test_required", test_required),
        ("test_requiredToOptional", test_requiredToOptional),
        ("test_withAddedAllowedValues", test_withAddedAllowedValues),
        ("test_withAddedExample", test_withAddedExample),
        ("test_withInitalAllowedValues", test_withInitalAllowedValues),
        ("test_withInitialExample", test_withInitialExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SchemaObjectTests.__allTests__SchemaObjectTests),
    ]
}
#endif
