#if !canImport(ObjectiveC)
import XCTest

extension OpenAPITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OpenAPITests = [
        ("test_Tmp", test_Tmp),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(OpenAPITests.__allTests__OpenAPITests),
    ]
}
#endif
