name: Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        # TODO: replace the documentation generator with something that is still maintained.

#      - name: Generate Documentation
#        uses: SwiftDocOrg/swift-doc@master
#        with:
#          inputs: Sources
#          module-name: OpenAPIKit
#          output: Documentation
#      - name: Upload Documentation to Wiki
#        uses: SwiftDocOrg/github-wiki-publish-action@v1
#        with:
#          path: Documentation
#        env:
#          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
