name: Documentation

on:
  push:
    branches:
      - release/4_0
      # ^ for now, we only want to use the v4.0 release branch.

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: swift:5.10

    steps:
      - uses: actions/checkout@v4
      - name: Build Docs
        run: |
          mkdir -p ./gh-pages
          swift package --allow-writing-to-directory ./gh-pages/docs \
            generate-documentation --include-extended-types \
                                   --disable-indexing \
                                   --output-path ./gh-pages/docs \
                                   --transform-for-static-hosting \
                                   --hosting-base-path OpenAPIKit \
                                   --target OpenAPIKit
      - name: Install rsync
        run: |
          apt-get update && apt-get install -y rsync
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.8
        with:
          folder: gh-pages
          branch: gh-pages

